[build]
  command = "npm install"
  publish = "."
  functions = "functions"

[dev]
  framework = "#custom"
  targetPort = 8888
  port = 8888
  publish = "."
  command = "python -m http.server 8888"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
